name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: kuro112/casinoadmin:backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: kuro112
        password: mike22

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: backend
